DATASET = "archive/dataset_Diseases_and_Symptoms.csv"
SYMPTOM_FILE = "archive/all_symptoms.csv"
VEC_FILE = "symptom_vectors.npy"
INDEX_FILE = "symptom_index.faiss"
MAP_FILE = "symptom_map.pkl"
EMBED_MODEL = "pritamdeka/BioBERT-mnli-snli-scinli-scitail-mednli-stsb"
RFC_MODEL = "models/clf-imbalanced.pkl"
BG_IMAGE_PATH = "archive/bg.png"